cluster.name: opensearch-cluster

network.host: 0.0.0.0

plugins.security.ssl.http.enabled_protocols: ["TLSv1.2"]
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: /usr/share/opensearch/config/certs/rest.pem
plugins.security.ssl.http.pemkey_filepath: /usr/share/opensearch/config/certs/rest.key
plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/opensearch/config/certs/ca.crt
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.pemcert_filepath: /usr/share/opensearch/config/certs/transport.pem
plugins.security.ssl.transport.pemkey_filepath: /usr/share/opensearch/config/certs/transport.key
plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/opensearch/config/certs/ca.crt

plugins.security.allow_unsafe_democertificates: false
plugins.security.allow_default_init_securityindex: false

plugins.security.audit.type: log4j
plugins.security.audit.config.log4j.logger_name: audit
plugins.security.audit.config.log4j.level: INFO

plugins.security.authcz.admin_dn: ["CN=admin,O=Dev,L=Rennes,ST=France,C=FR"]

plugins.security.restapi.roles_enabled: ["all_access","app_rw_role","app_ro_role"]
