_meta:
  type: "rolesmapping"
  config_version: 2

all_access:
  reserved: false
  users:
    - "admin"
  backend_roles:
    - "admin"

app_rw_role:
  reserved: false
  users:
    - "app_rw"
  backend_roles:
    - "user"

app_ro_role:
  reserved: false
  users:
    - "app_ro"
  backend_roles:
    - "user"
