_meta:
  type: "roles"
  config_version: 2

app_ro_role:
  cluster_permissions:
    - "cluster_composite_ops_ro"
  index_permissions:
    - index_patterns:
        - "*-index"
      allowed_actions:
        - "read"
        - "indices:admin/get"
        - "indices:admin/mappings/get"
        - "indices:admin/settings/get"

app_rw_role:
  cluster_permissions:
    - "cluster_composite_ops"
  index_permissions:
    - index_patterns:
        - "*-index"
      allowed_actions:
        - "crud"
        - "indices:admin/get"
        - "indices:admin/mappings/get"
        - "indices:admin/settings/get"
